version: 2
jobs:
  build:
    docker:
      - image: node:7
      - image: ruby:2.1-onbuild
    working_directory: ~/ionic-site/
    steps:
      - restore_cache:
         key: main_code
      - checkout
      - save_cache:
         key: main_code
         paths:
           - ~/ionic-site/
      - restore_cache:
         key: node_modules_{{ checksum "package.json" }}
      - run: npm i
      - save_cache:
         key: node_modules_{{ checksum "package.json" }}
         paths:
           - ~/ionic-site/node_modules/
      #- restore_cache:
      #   key: rvm_{{ checksum "package.json" }}
      - run: bundle install
      #- run: ./_scripts/prepare.sh
      #- save_cache:
      #   key: rvm_{{ checksum "package.json" }}
      #   paths:
      #     - ~/.rvm
      - run: ./scripts/test.sh
      #- run: ./_scripts/deploy_staging.sh
